// lib/events.ts

import {
  addDoc,
  collection,
  doc,
  getDocs,
  limit,
  orderBy,
  query,
  serverTimestamp,
  where,
} from "firebase/firestore";
import { db } from "@/lib/firebase";
import type { LogType } from "@/lib/caseManagement";

export type EventVisibility =
  | "private"
  | "case_shared"
  | "selected_users"
  | "global";

export type EventSource = "manual" | "case_log" | "charge" | "system";

export type EventStatus = "active" | "cancelled" | "completed";

export type CalendarEventDoc = {
  title: string;
  description?: string;

  startAt: any;
  endAt?: any;
  allDay?: boolean;

  color?: string;

  visibility: EventVisibility;

  ownerUid: string;
  ownerEmail?: string;

  visibleToUids?: string[];
  caseParticipantsSnapshot?: string[];

  caseRef?: {
    caseId?: string | null;
    caratula?: string;
  };

  source: EventSource;
  sourceRef?: {
    logId?: string | null;
    chargeId?: string | null;
    scheduledChargeId?: string | null;
  };

  autoGenerated?: boolean;
  autoType?: string;

  location?: string;
  meetingUrl?: string;

  reminderMinutesBefore?: number[];

  status: EventStatus;

  externalSync?: {
    provider?: "google";
    enabled?: boolean;
    syncStatus?: "pending" | "synced" | "error";
    externalEventId?: string;
    lastSyncedAt?: any;
    lastError?: string;
  };

  createdAt?: any;
  createdByUid?: string;
  createdByEmail?: string;
  updatedAt?: any;
  rescheduled?: boolean;
rescheduledLabel?: string;
reprogrammedAt?: any;
reprogrammedByUid?: string;
reprogrammedByEmail?: string;
reprogrammedToEventId?: string | null;
reprogrammedToStartAt?: any;
reprogrammedToEndAt?: any;
reprogrammedFromEventId?: string | null;
};

export type CalendarEventRow = CalendarEventDoc & {
  id: string;
};

export function eventsColRef() {
  return collection(db, "events");
}

export function eventDocRef(eventId: string) {
  return doc(db, "events", eventId);
}

export function normalizeEventVisibleToUids(args: {
  ownerUid: string;
  visibility: EventVisibility;
  selectedUids?: string[];
  caseParticipantUids?: string[];
}) {
  const ownerUid = String(args.ownerUid ?? "").trim();
  const selected = Array.isArray(args.selectedUids) ? args.selectedUids : [];
  const caseParticipants = Array.isArray(args.caseParticipantUids)
    ? args.caseParticipantUids
    : [];

  if (args.visibility === "global") return [];

  if (args.visibility === "private") {
    return ownerUid ? [ownerUid] : [];
  }

  if (args.visibility === "case_shared") {
    return Array.from(new Set([ownerUid, ...caseParticipants].filter(Boolean)));
  }

  return Array.from(new Set([ownerUid, ...selected].filter(Boolean)));
}

function cleanObject<T extends Record<string, any>>(obj: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(obj).filter(([, value]) => value !== undefined)
  ) as Partial<T>;
}

export async function createCalendarEvent(params: {
  title: string;
  description?: string;
  startAt: Date;
  endAt?: Date;
  allDay?: boolean;
  color?: string;

  visibility: EventVisibility;

  ownerUid: string;
  ownerEmail?: string;

  selectedUserUids?: string[];
  caseParticipantUids?: string[];

  caseRef?: {
    caseId?: string | null;
    caratula?: string;
  };

  source?: EventSource;
  sourceRef?: {
    logId?: string | null;
    chargeId?: string | null;
    scheduledChargeId?: string | null;
  };

  autoGenerated?: boolean;
  autoType?: string;

  location?: string;
  meetingUrl?: string;

  reminderMinutesBefore?: number[];

  status?: EventStatus;
}) {
  const visibleToUids = normalizeEventVisibleToUids({
    ownerUid: params.ownerUid,
    visibility: params.visibility,
    selectedUids: params.selectedUserUids,
    caseParticipantUids: params.caseParticipantUids,
  });

  const caseRef =
    params.caseRef &&
    (params.caseRef.caseId !== undefined || params.caseRef.caratula !== undefined)
      ? cleanObject({
          caseId: params.caseRef.caseId ?? null,
          caratula: params.caseRef.caratula ?? "",
        })
      : undefined;

  const sourceRef =
    params.sourceRef &&
    (params.sourceRef.logId !== undefined ||
      params.sourceRef.chargeId !== undefined ||
      params.sourceRef.scheduledChargeId !== undefined)
      ? cleanObject({
          logId: params.sourceRef.logId ?? null,
          chargeId: params.sourceRef.chargeId ?? null,
          scheduledChargeId: params.sourceRef.scheduledChargeId ?? null,
        })
      : undefined;

  const docData: any = cleanObject({
    title: String(params.title ?? "").trim(),
    description: String(params.description ?? "").trim(),
    startAt: params.startAt,
    endAt: params.endAt ?? null,
    allDay: Boolean(params.allDay),
    color: String(params.color ?? "").trim() || "#3b82f6",

    visibility: params.visibility,

    ownerUid: params.ownerUid,
    ownerEmail: params.ownerEmail ?? "",

    visibleToUids,
    caseParticipantsSnapshot:
      params.visibility === "case_shared"
        ? Array.from(new Set((params.caseParticipantUids ?? []).filter(Boolean)))
        : [],

    caseRef,
    source: params.source ?? "manual",
    sourceRef,

    autoGenerated: Boolean(params.autoGenerated),
    autoType: params.autoType ?? "",

    location: params.location ?? "",
    meetingUrl: params.meetingUrl ?? "",

    reminderMinutesBefore: Array.isArray(params.reminderMinutesBefore)
      ? params.reminderMinutesBefore
      : [],

    status: params.status ?? "active",

    externalSync: {
      provider: "google",
      enabled: false,
      syncStatus: "pending",
      externalEventId: "",
      lastSyncedAt: null,
      lastError: "",
    },

    createdAt: serverTimestamp(),
    createdByUid: params.ownerUid,
    createdByEmail: params.ownerEmail ?? "",
    updatedAt: serverTimestamp(),
  });

  const ref = await addDoc(eventsColRef(), docData);
  return ref.id;
}

export function getAutoEventColorForLogType(logType: LogType) {
  switch (logType) {
    case "vencimiento":
      return "#ef4444";
    case "audiencia":
      return "#f97316";
    case "control_cobro":
      return "#22c55e";
    case "reunion_parte":
      return "#3b82f6";
    case "sentencia":
      return "#a855f7";
    case "informativa":
    default:
      return "#6b7280";
  }
}

export async function createAutoEventFromCaseLog(params: {
  caseId: string;
  caratula?: string;
  ownerUid: string;
  ownerEmail?: string;
  caseParticipantUids: string[];
  logId: string;
  logType: LogType;
  title: string;
  body?: string;
  startAt: Date;
  endAt?: Date;
  location?: string;
}) {
  return createCalendarEvent({
    title: String(params.title ?? "").trim(),
    description: String(params.body ?? "").trim(),
    startAt: params.startAt,
    endAt: params.endAt,
    color: getAutoEventColorForLogType(params.logType),
    visibility: "case_shared",
    ownerUid: params.ownerUid,
    ownerEmail: params.ownerEmail ?? "",
    caseParticipantUids: params.caseParticipantUids,
    caseRef: {
      caseId: params.caseId,
      caratula: params.caratula ?? "",
    },
    source: "case_log",
    sourceRef: {
      logId: params.logId,
    },
    autoGenerated: true,
    autoType: `case_log_${params.logType}`,
    location: params.location ?? "",
    reminderMinutesBefore: [60],
    status: "active",
  });
}

export async function listUpcomingEventsForUser(params: {
  uid: string;
  maxResults?: number;
}) {
  const maxResults = Math.max(1, Math.min(100, Number(params.maxResults ?? 20)));
  const now = new Date();

  const qPersonal = query(
    eventsColRef(),
    where("visibleToUids", "array-contains", params.uid),
    where("status", "==", "active"),
    orderBy("startAt", "asc"),
    limit(100)
  );

  const qGlobal = query(
    eventsColRef(),
    where("visibility", "==", "global"),
    where("status", "==", "active"),
    orderBy("startAt", "asc"),
    limit(100)
  );

  const [personalSnap, globalSnap] = await Promise.all([getDocs(qPersonal), getDocs(qGlobal)]);

  const map = new Map<string, CalendarEventRow>();

  [...personalSnap.docs, ...globalSnap.docs].forEach((d) => {
    map.set(d.id, { id: d.id, ...(d.data() as any) });
  });

  return Array.from(map.values())
    .filter((row) => {
      const raw = row.startAt;
      const d = raw?.toDate ? raw.toDate() : new Date(raw);
      return d instanceof Date && !Number.isNaN(d.getTime()) && d.getTime() >= now.getTime();
    })
    .sort((a, b) => {
      const aa = a.startAt?.toDate ? a.startAt.toDate().getTime() : new Date(a.startAt).getTime();
      const bb = b.startAt?.toDate ? b.startAt.toDate().getTime() : new Date(b.startAt).getTime();
      return aa - bb;
    })
    .slice(0, maxResults);
}